version: "3.7"
services:

  crawler:
    container_name: crawler
    build:
      context: crawler
    depends_on:
      - postgres
    environment:
        ENVIRONMENT: ${ENVIRONMENT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_SSL: ${POSTGRES_SSL}
        SERVER_PORT: 8016
    ports:
        - 8016:8016

  ai-engine:
    container_name: ai-engine
    build:
      context: ai-engine
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL: ${POSTGRES_SSL}
      SERVER_PORT: 8016
    ports:
        - 8000:8000