version: "3"
services:

  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
        - "5433:5432" # Exposing Postgres on different port for convenience
    environment:
        POSTGRES_DB: "little-birds"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
    volumes:
        - postgres-data:/data
    restart: always

    #   mongodb:
    #     container_name: mongodb
    #     image: postgres
    #     ports:
    #         - "" # Exposing Postgres on different port for convenience
    #     environment:
    #         POSTGRES_DB: "little-birds"
    #         POSTGRES_USER: "postgres"
    #         POSTGRES_PASSWORD: "password"
    #     volumes:
    #         - postgres-data:/data
    #     restart: always

    # rabbit:
    #   container_name: rabbit
    #   image: rabbitmq:3-management
    #   ports:
    #       - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    #   restart: always

    # scraper-worker:
    #   container_name: scraper-worker
    #   build:
    #     context: scraper-worker
    #   depends_on:
    #     - rabbit
    #     - postgresdb
    #   environment:
    #       REDIS_HOST: "redis"
    #       REDIS_PORT: "6379"
    #       RABBIT_PASSWORD: "guest"
    #       RABBIT_USER: "guest"
    #       RABBIT_HOST: "rabbit"
    #       RABBIT_PORT: "5672"
    #       RABBIT_MANAGEMENT_PORT: "15672"
    #       DB_PASSWORD: "password"
    #       DB_USER: "postgres"
    #       DB_HOST: "postgres"
    #       DB_NAME: "little-birds"

  scraper-manager:
    container_name: scraper-manager
    build:
      context: scraper-manager
    depends_on:
        # - rabbit
      - postgresdb
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
        DB_PASSWORD: "password"
        DB_USER: "postgres"
        DB_HOST: "postgres"
        DB_NAME: "little-birds"

volumes:
  postgres-data:

